### PR TITLE
Automatically run devtests with docker

### PR DESCRIPTION
**Pull request by wenzowski**
A much improved version of #18 which does not require mucking around in dashboards for build environment because all environment is specified by the docker layer chain.

The test code has been modified to `System.exit(1)` on error, so we can detect it automatically with Circle.

This includes instructions on how to boot and test using docker-compose, which automatically pulls down the specified version of elasticsearch.

closes #18
closes #15
closes #14

### CODE REVIEW

**Comment by wenzowski** [comment]
@KnowledgeGarden how does this look?

**Comment by KnowledgeGarden** [comment]
Just make sure I didn't push changes before merging. I'm more than ok with what is being done here.

**Comment by wenzowski** [comment]
Great! I actually just rebased this

**Comment by KnowledgeGarden** [comment]
Ok. I  just did a fresh pull and will be running it now.

**Pull request merged**
